[package]
name = "rustplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bench = []

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
kiss3d = "0.32"
itertools = "0.10"
rand = "0.8"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "iter"
harness = false

[[bench]]
name = "loop"
harness = false
